### ISSUE TITLE
Is there anyway to manually control the spatial navigation?

### ISSUE THREAD

**Issue by EloB** [linuxenko/spatial-virtual-dom#1]
I'm using the your `SpatialNavigator` in React. Have some troubles to figure out how to use it manually. It works great on simple solutions but I have a infinite carousel to elements get added later on. This actually works but sometimes I have timing issues and that messes up the focus (like other focusable element gets focused that isn't part of the carousel).
Is there anyway to use your `SpatialNavigator` to manually control which element should have focus?

I been trying to cancel `unfocussn` but it's still triggers `focussn` on the next element. https://github.com/linuxenko/spatial-virtual-dom/blob/master/lib/spatial.js#L747

**Comment by linuxenko** [comment]
Hi @EloB 

Check out [this demo](https://github.com/c0ncept/igogo-TV) application, there is all kinds of carousel implementations.

**Comment by EloB** [comment]
Hello @linuxenko thanks for your reply.

I can't find any infinity carousels there. My carousel has "unlimited items" and will only repeat on both ends of the carousel. I'm reusing some of the already existing divs and *sometimes* there is timing issue so the spatial navigation "misses" the correct next item in the unlimited carousel.
